services:
  - type: web
    name: tengacion
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build --prefix frontend && npm run build --prefix backend
    startCommand: npm install && npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
