services:
  - type: web
    name: tengacion
    env: node
    plan: free
    rootDir: .
    buildCommand: npm run build
    startCommand: npm install && npm install --prefix backend && npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"

